name: Cypress Parallel Tests

on:
  workflow_dispatch:

jobs:
  cypress-run:
    runs-on: windows-latest

    strategy:
      fail-fast: false
      matrix:
        containers: [1, 2]

    steps:
      - uses: actions/checkout@v4

      - uses: cypress-io/github-action@v6
        with:
          record: true
          parallel: true
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}