name: Run Cypress Tests

on: [push]

jobs:
  cypress-run:
    runs-on: windows-latest   # or ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: cypress-io/github-action@v6
        with:
          record: true   # 👈 enables Cypress Cloud
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}